# Generated by Django 2.2.5 on 2019-09-17 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100)),
                ('salary', models.CharField(max_length=20)),
                ('organization', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200, null=True)),
                ('employment', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(max_length=1000)),
                ('skills', models.CharField(max_length=100, null=True)),
                ('requirements', models.TextField(max_length=1000, null=True)),
                ('duties', models.TextField(max_length=1000, null=True)),
                ('conditions', models.CharField(max_length=1000, null=True)),
            ],
        ),
    ]
