# Generated by Django 2.2.5 on 2019-09-17 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_vacancy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='conditions',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
